version: '3.3'

services:

    dbase:
        image: mysql:5.7
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: app_wp
            MYSQL_USER: dev
            MYSQL_PASSWORD: development

    www:
        depends_on:
            - dbase
        image: wordpress:latest
        ports:
            - 80:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: dbase:3306
            WORDPRESS_DB_USER: dev
            WORDPRESS_DB_PASSWORD: development
            WORDPRESS_DB_NAME: app_wp
        volumes:
            - ./app:/var/www/html
            
    phpmyadmin:
        image: phpmyadmin
        restart: always
        links:
            - dbase
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1